# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/


title: "Max Michael Andersson"
subtitle: "Research focused on chemosensory receptors and functional genomics, disease vector management, peripheral neuroethology in mosquitoes."
description: "Chemosensory receptors and molecular interactions with cognate chemical ligands, disease vector management, peripheral neuroethology in mosquitoes."
author: "Max"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-feed
  - jekyll-include-cache

